-- MySQL Script generated by MySQL Workbench
-- Fri Jun 18 22:39:14 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema base_dados
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema base_dados
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `base_dados` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `base_dados` ;

-- -----------------------------------------------------
-- Table `base_dados`.`TABELA_DIMENSAO_VENDENDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_dados`.`TABELA_DIMENSAO_VENDENDOR` (
  `VendendorCodigo` INT NOT NULL,
  `VendendorNome` VARCHAR(20) NULL DEFAULT NULL,
  `VendendorSexo` INT NULL DEFAULT NULL,
  `VendedorComissao` DECIMAL(19,2) NULL DEFAULT NULL,
  `VendedorMatricula` INT NULL DEFAULT NULL,
  PRIMARY KEY (`VendendorCodigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `base_dados`.`DIMENSA_CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_dados`.`DIMENSA_CLIENTE` (
  `ClienteCodigo` INT NOT NULL,
  `NomeCliente` VARCHAR(100) NULL DEFAULT NULL,
  `ClienteCidade` VARCHAR(45) NULL DEFAULT NULL,
  `ClienteEstado` VARCHAR(45) NULL DEFAULT NULL,
  `ClientePais` VARCHAR(45) NULL DEFAULT NULL,
  `dimensao_VendedorCodigo` INT NOT NULL,
  PRIMARY KEY (`ClienteCodigo`),
  INDEX `fk_dim_cliente_dim_vendedor1_idx` (`dimensao_VendedorCodigo` ASC) VISIBLE,
  CONSTRAINT `fk_dim_cliente_dim_vendedor1`
    FOREIGN KEY (`dimensao_VendedorCodigo`)
    REFERENCES `base_dados`.`TABELA_DIMENSAO_VENDENDOR` (`VendendorCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `base_dados`.`Tabela_DIMENSAO_DEPENDENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_dados`.`Tabela_DIMENSAO_DEPENDENTE` (
  `DependenteCodigo` INT NOT NULL,
  `DependenteNome` VARCHAR(20) NULL DEFAULT NULL,
  `DepententeNascimentoData` DATETIME NULL DEFAULT NULL,
  `DependenteSexo` INT NOT NULL DEFAULT '0',
  `MatriculaFuncionario` INT NULL DEFAULT NULL,
  `dimensao_VendendorCodigo` INT NOT NULL,
  PRIMARY KEY (`DependenteCodigo`),
  INDEX `fk_dim_dependente_dim_vendedor_idx` (`dimensao_VendendorCodigo` ASC) VISIBLE,
  CONSTRAINT `fk_dim_dependente_dim_vendedor`
    FOREIGN KEY (`dimensao_VendendorCodigo`)
    REFERENCES `base_dados`.`TABELA_DIMENSAO_VENDENDOR` (`VendendorCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `base_dados`.`DIMENSAO_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_dados`.`DIMENSAO_produto` (
  `ProdutoCodigo` INT NOT NULL,
  `ProdutoNome` VARCHAR(45) NULL DEFAULT NULL,
  `ProdutoTipo` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`ProdutoCodigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `base_dados`.`TABELA_FATO_VENDA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_dados`.`TABELA_FATO_VENDA` (
  `CodigoVenda` INT NOT NULL,
  `DataVenda` DATETIME NULL DEFAULT NULL,
  `CodigoCliente` INT NULL DEFAULT NULL,
  `CondigoProduto` INT NULL DEFAULT NULL,
  `CodigoVendedor` INT NULL DEFAULT NULL,
  `Quantidade` INT NULL DEFAULT NULL,
  `ValorUnitario` DECIMAL(19,2) NULL DEFAULT NULL,
  `dimensao_VendendorCodigo` INT NOT NULL,
  PRIMARY KEY (`CodigoVenda`),
  INDEX `fk_fato_venda_dim_vendedor1_idx` (`dimensao_VendendorCodigo` ASC) VISIBLE,
  CONSTRAINT `fk_fato_venda_dim_vendedor1`
    FOREIGN KEY (`dimensao_VendendorCodigo`)
    REFERENCES `base_dados`.`TABELA_DIMENSAO_VENDENDOR` (`VendendorCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `base_dados`.`TABELA_FATO_VENDA_DIMENSAO_PRODUTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `base_dados`.`TABELA_FATO_VENDA_DIMENSAO_PRODUTO` (
  `FATO_CodigoVenda` INT NOT NULL,
  `DIMENSAO_CodigoProduto` INT NOT NULL,
  PRIMARY KEY (`FATO_CodigoVenda`, `DIMENSAO_CodigoProduto`),
  INDEX `fk_fato_venda_has_dim_produto_dim_produto1_idx` (`DIMENSAO_CodigoProduto` ASC) VISIBLE,
  INDEX `fk_fato_venda_has_dim_produto_fato_venda1_idx` (`FATO_CodigoVenda` ASC) VISIBLE,
  CONSTRAINT `fk_fato_venda_has_dim_produto_fato_venda1`
    FOREIGN KEY (`FATO_CodigoVenda`)
    REFERENCES `base_dados`.`TABELA_FATO_VENDA` (`CodigoVenda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fato_venda_has_dim_produto_dim_produto1`
    FOREIGN KEY (`DIMENSAO_CodigoProduto`)
    REFERENCES `base_dados`.`DIMENSAO_produto` (`ProdutoCodigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
